[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f5f7"
textColor = "#0b0b0b"
